POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuário 5",
  "email": "usuario5@email.com",
  "referral": "290ab628-4f62-41dd-a53b-d79dcfde525f"
}

###

GET http://localhost:3333/invites/290ab628-4f62-41dd-a53b-d79dcfde525f

### 

GET http://localhost:3333/subscribers/290ab628-4f62-41dd-a53b-d79dcfde525f/ranking/clicks

###

GET http://localhost:3333/subscribers/075ff07e-f227-4e80-ac78-766dd78ace6c/ranking/count

###

GET http://localhost:3333/subscribers/075ff07e-f227-4e80-ac78-766dd78ace6c/ranking/position

###

GET http://localhost:3333/ranking

###

POST http://localhost:3333/messages
Content-Type: application/json

{
  "message": "Me diga o nome dos usuários que não conseguiram convidar ninguém pro evento!"
}
